<script setup>
import { reactive } from 'vue';
import { ccCall } from '../../api/cc';
const props=defineProps({config:Object});
const state=reactive({});
function draft(agent){return state[agent.agent]||(state[agent.agent]={...agent,allowed_sources:[...(agent.allowed_sources||[])],busy:false,error:'',notice:''})}
async function save(agent){const row=draft(agent);row.busy=true;row.error='';row.notice='';try{const result=await ccCall('lead_assignment_configuration',{action:'save_agent',agent:agent.agent,auto_enabled:Number(row.auto_enabled),temporarily_stopped:Number(row.temporarily_stopped),use_conversion:Number(row.use_conversion),max_per_day:row.max_per_day,share_weight:row.share_weight,lead_sources:row.allowed_sources.join(', '),stop_reason:row.stop_reason,team_leader:row.team_leader||''});if(!result.saved)throw new Error('Assignment settings were not saved.');row.notice='Saved';}catch(error){row.error=error.message}finally{row.busy=false}}
</script>
<template>
<section v-if="config" class="assignment-editor">
  <div class="assignment-mode"><span>Mode: <b>{{config.settings?.assignment_mode}}</b></span><span>Hours: <b>{{config.settings?.start_time}} – {{config.settings?.end_time}}</b></span><span>Performance: <b>Last {{config.settings?.conversion_window_days}} days</b></span><span>Conversion Status: <b>{{config.settings?.conversion_statuses}}</b></span></div>
  <p class="assignment-rule"><b>Assignment rule:</b> Only an active Business Executive who is checked in, enabled, mapped to the Lead Source and below the daily limit is eligible. The lowest weighted assignment score receives the next lead.</p>
  <article v-for="agent in config.agents||[]" :key="agent.agent" class="assignment-agent">
    <form @submit.prevent="save(agent)"><div class="assignment-fields">
      <div><small>AGENT &amp; ATTENDANCE</small><strong>{{agent.employee_name}}</strong><span>{{agent.agent}}</span><b class="assignment-attendance">{{agent.checked_in?'CHECKED IN':'NOT CHECKED IN'}}</b></div>
      <label><small>ALLOWED LEAD SOURCES</small><select multiple v-model="draft(agent).allowed_sources" size="4"><option v-for="source in config.source_options||[]" :key="source">{{source}}</option></select><span>Ctrl/Cmd + click to select multiple sources</span></label>
      <label><small>TODAY / DAILY LIMIT</small><div class="assignment-inline"><strong>{{agent.today_assigned||0}}</strong> / <input v-model.number="draft(agent).max_per_day" type="number" min="0" required></div><span>Assigned today / maximum</span></label>
      <div><small>CONVERSION PERFORMANCE</small><label class="assignment-inline"><input type="checkbox" v-model="draft(agent).use_conversion" :true-value="1" :false-value="0"> Use performance</label><label class="assignment-inline">Weight <input v-model.number="draft(agent).share_weight" type="number" min="0.01" step="0.01" required></label></div>
      <label><small>AUTO ASSIGNMENT</small><input class="assignment-switch" type="checkbox" v-model="draft(agent).auto_enabled" :true-value="1" :false-value="0"><span>Auto assign</span></label>
      <div><label><small>TEMPORARY STOP</small><input class="assignment-switch" type="checkbox" v-model="draft(agent).temporarily_stopped" :true-value="1" :false-value="0"></label><input v-if="draft(agent).temporarily_stopped" v-model="draft(agent).stop_reason" placeholder="Stop reason" aria-label="Stop reason"></div>
      <label v-if="config.is_manager"><small>TEAM LEADER</small><input v-model="draft(agent).team_leader" type="email" placeholder="Team leader user"></label>
    </div><footer><p v-if="draft(agent).error" role="alert">{{draft(agent).error}}</p><span v-if="draft(agent).notice" role="status">{{draft(agent).notice}}</span><button class="cc-primary" :disabled="draft(agent).busy">{{draft(agent).busy?'Saving…':'Save changes'}}</button></footer></form>
  </article>
</section>
</template>
<style scoped>
.assignment-editor{min-width:0}.assignment-mode{display:flex;flex-wrap:wrap;gap:14px;padding:16px 20px;background:#fcf5dd;border-bottom:1px solid #e9d691;font-size:12px}.assignment-rule{padding:16px 20px;font-size:12px;line-height:1.7;background:#faf8ee}.assignment-agent{margin:16px 0;border:1px solid #ded7c8;border-left:4px solid #ba971b;border-radius:16px;padding:20px;background:white}.assignment-fields{display:grid;grid-template-columns:1.2fr 1.4fr .8fr 1fr .7fr .8fr;gap:16px;overflow:auto}.assignment-fields>div,.assignment-fields>label{display:flex;flex-direction:column;gap:10px;min-width:130px;border-right:1px solid #dce5de;padding-right:16px}.assignment-fields small{font-size:9px;font-weight:800;letter-spacing:1.3px;color:#87998f}.assignment-fields strong{font-size:16px;color:#12382b}.assignment-fields span{font-size:11px;color:#7c9086}.assignment-fields select{width:100%;min-width:190px;min-height:130px;padding:6px;border:1px solid #d5cfbf;border-radius:12px}.assignment-fields select option{padding:7px;border-radius:6px}.assignment-fields input:not([type=checkbox]){width:100%;min-width:0;border:1px solid #d5cfbf;border-radius:10px;padding:10px}.assignment-inline{display:flex;align-items:center;gap:8px;font-size:12px}.assignment-inline input[type=number]{max-width:75px}.assignment-switch{appearance:none!important;width:52px!important;height:28px!important;border-radius:20px!important;background:#d2cdbf!important;border:0!important;position:relative;cursor:pointer}.assignment-switch:after{content:'';position:absolute;width:22px;height:22px;top:3px;left:3px;border-radius:50%;background:white;transition:transform .15s}.assignment-switch:checked{background:#197c52!important}.assignment-switch:checked:after{transform:translateX(24px)}.assignment-attendance{font-size:9px;border:1px solid #d5cfbf;background:#f5f0e4;border-radius:15px;padding:4px 8px;align-self:flex-start}.assignment-agent footer{display:flex;align-items:center;justify-content:flex-end;gap:12px;margin-top:14px;font-size:12px}.assignment-agent footer p{color:#ad302b}@media(max-width:900px){.assignment-fields{grid-template-columns:repeat(2,minmax(0,1fr));overflow:visible}.assignment-fields>div,.assignment-fields>label{min-width:0}.assignment-fields select{min-width:0}}@media(max-width:500px){.assignment-fields{grid-template-columns:1fr}}
</style>
