<script setup>
import {ref,computed,onMounted} from 'vue';
import {ccCall} from '../../api/cc';
import {dateRange,maskPhone} from '../../lib/cc';
const rows=ref([]),manager=ref(false),busy=ref(false),error=ref(''),notice=ref(''),search=ref(''),field=ref('posting_date'),from=ref(''),to=ref(''),revealed=ref(null);
const columns=[['posting_date','Posting Date','date'],['client_name','Client Name','text'],['mobile','Mobile','text'],['area','Area','text'],['enquired_for','Enquired For','text'],['status','Status','text'],['followup_date','Follow-up','date'],['notes','Notes','text']];
function preset(value){const today=dateRange('today')[0];if(value==='all'){from.value='';to.value='';return}if(value==='today'){from.value=to.value=today;return}const date=new Date(today+'T12:00:00Z');date.setUTCDate(date.getUTCDate()-((date.getUTCDay()+6)%7)-(value==='last_week'?7:0));from.value=date.toISOString().slice(0,10);date.setUTCDate(date.getUTCDate()+6);to.value=date.toISOString().slice(0,10)}
const visible=computed(()=>rows.value.filter(row=>(!from.value||String(row[field.value]||'')>=from.value)&&(!to.value||String(row[field.value]||'')<=to.value)&&(!search.value.trim()||columns.some(([key])=>String(row[key]||'').toLowerCase().includes(search.value.trim().toLowerCase())))));
async function load(){const result=await ccCall('cc_worksheet',{action:'list'});rows.value=result.rows||[];manager.value=!!result.manager_view}
async function action(callback){busy.value=true;error.value='';try{await callback()}catch(e){error.value=e.message}finally{busy.value=false}}
function add(){rows.value.unshift({posting_date:dateRange('today')[0],client_name:'',mobile:'',area:'',enquired_for:'',status:'',followup_date:'',notes:''});preset('all')}
async function save(){await action(async()=>{const values=rows.value.filter(row=>String(row.client_name||'').trim()).map((row,index)=>({...row,row_order:index}));if(!values.length)throw new Error('Add a client name before saving.');const result=await ccCall('cc_worksheet',{action:'save',rows:JSON.stringify(values)});notice.value=`Saved — ${result.created||0} new, ${result.saved||0} updated`;await load()})}
async function remove(row){await action(async()=>{if(row.name)await ccCall('cc_worksheet',{action:'delete',name:row.name});rows.value=rows.value.filter(item=>item!==row)})}
function exportCsv(){const cols=manager.value?[['owner','Agent'],...columns]:columns;const escape=value=>'"'+String(value??'').replaceAll('"','""')+'"';const lines=[cols.map(([,label])=>label),...rows.value.map(row=>cols.map(([key])=>row[key]))];const url=URL.createObjectURL(new Blob([lines.map(line=>line.map(escape).join(',')).join('\n')],{type:'text/csv'}));const link=document.createElement('a');link.href=url;link.download='cc-worksheet.csv';link.click();URL.revokeObjectURL(url)}
preset('this_week');onMounted(()=>action(load));
</script>
<template><section class="cc-card"><header>📊 My Worksheet <input v-model="search" placeholder="Search…"><button :disabled="busy" @click="add">＋ Add Row</button><button :disabled="busy" @click="save">💾 Save</button><button @click="exportCsv">⬇ Export CSV</button></header><div class="cc-queue-filters"><label>Filter <select v-model="field"><option value="posting_date">Posting Date</option><option value="followup_date">Follow-up</option></select></label><input v-model="from" type="date" aria-label="From"><input v-model="to" type="date" aria-label="To"><button v-for="[key,label] in [['this_week','This Week'],['last_week','Last Week'],['today','Today'],['all','All']]" :key="key" @click="preset(key)">{{label}}</button></div><p class="cc-note">Click a cell to edit, then Save. {{manager?'Manager view — all agents.':''}} Mobile numbers are masked; focus a mobile field to reveal.</p><p v-if="busy" role="status">Working…</p><p v-if="error" class="cc-error" role="alert">{{error}}</p><p v-if="notice" role="status">{{notice}}</p><div class="tbl-wrap"><table class="cc-simple-table"><thead><tr><th v-if="manager">Agent</th><th v-for="[key,label] in columns" :key="key">{{label}}</th><th>Action</th></tr></thead><tbody><tr v-for="row in visible" :key="row.name||rows.indexOf(row)"><td v-if="manager">{{row.owner||'—'}}</td><td v-for="[key,label,type] in columns" :key="key"><input :aria-label="label" :type="type" :disabled="busy" :value="key==='mobile'&&revealed!==row?maskPhone(row[key]):row[key]" @focus="key==='mobile'&&(revealed=row)" @blur="revealed=null" @input="row[key]=$event.target.value"></td><td><button :disabled="busy" @click="remove(row)">Delete</button></td></tr><tr v-if="!visible.length&&!busy"><td colspan="10">No worksheet rows match these filters.</td></tr></tbody></table></div></section></template>
<style scoped>header{display:flex;gap:8px;flex-wrap:wrap;align-items:center}table{min-width:1100px}td input{min-width:100px;width:100%;padding:8px;border:1px solid transparent;border-radius:6px;background:transparent}td input:focus{border-color:#248050;background:white}header input{max-width:180px}</style>
