<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { apiCredentials, apiUrl } from '../api/config';
import { request } from '../api/http';
import { session } from '../lib/session';
import '../styles/sales-master-data.css';

const reportName='REFERRAL REPORT – FIXED', pageSize=20;
const cols=[['invoice','Invoice'],['posting_date','Posting Date'],['branch','Branch'],['customer','Customer'],['booking_type','Booking Type'],['sales_people','Sales Person'],['mode_of_payment','Mode of Payment'],['paid_amount','Paid w/ GST'],['tax_amount','GST Amt'],['paid_amount_without_tax','Paid w/o GST'],['grand_total','Grand Total'],['outstanding_amount','Outstanding']];
const presets=[['today','Today'],['yesterday','Yesterday'],['thismonth','This Month'],['lastmonth','Last Month'],['thisquarter','This Quarter'],['thisfy','This Financial Year']];
const from=ref(''),to=ref(''),quick=ref('thismonth'),branch=ref(''),salesPerson=ref(''),bookingType=ref(''),modeOfPayment=ref(''),customer=ref(''),paidFrom=ref(''),paidTo=ref(''),outstandingOperator=ref(''),outstandingValue=ref(''),format=ref('xlsx');
const permittedBranches=ref([]), allBranchAccess=ref(false), branchRestricted=ref(false), branchReady=ref(false), branchError=ref('');
const rows=ref([]), filteredRows=ref([]), employees=ref([]), loading=ref(false), error=ref(''), notice=ref(''), page=ref(1), reportLoaded=ref(false);
let controller, alive=true;
const pageCount=computed(()=>Math.max(1,Math.ceil(filteredRows.value.length/pageSize)));
const visibleRows=computed(()=>filteredRows.value.slice((page.value-1)*pageSize,page.value*pageSize));
const money=v=>'₹'+Number(v||0).toLocaleString('en-IN',{minimumFractionDigits:2,maximumFractionDigits:2});
const recordCount=computed(()=>`${filteredRows.value.length.toLocaleString('en-IN')} records`);
const canUseAll=()=>session.user==='Administrator'||session.roles.includes('System Manager');
function pad(v){return String(v).padStart(2,'0');}
function iso(date){return `${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`;}
function cycleRange(offset=0){const now=new Date();let month=now.getMonth()+(now.getDate()<6?-1:0)+offset;const start=new Date(now.getFullYear(),month,6);return{from:iso(start),to:iso(new Date(start.getFullYear(),start.getMonth()+1,5))};}
function dateRange(key){const now=new Date(),today=iso(now);if(key==='today')return{from:today,to:today};if(key==='yesterday'){now.setDate(now.getDate()-1);const y=iso(now);return{from:y,to:y};}if(key==='thismonth')return cycleRange();if(key==='lastmonth')return cycleRange(-1);if(key==='thisquarter'){const m=now.getMonth(),qStart=Math.floor(m/3)*3;return{from:iso(new Date(now.getFullYear(),qStart,6)),to:today};}if(key==='thisfy'){const year=now.getMonth()>=3?now.getFullYear():now.getFullYear()-1;return{from:`${year}-04-01`,to:`${year+1}-03-31`};}return cycleRange();}
function parseAmount(value){if(value===null||value===undefined||String(value).trim()==='')return null;const n=Number(String(value).replace(/[₹,\s]/g,''));return Number.isFinite(n)?n:null;}
function round(value){return Math.round((Number(value||0)+Number.EPSILON)*100)/100;}
function normalizeRow(row){const paid=Number(row.paid_amount||0);let without=parseAmount(row.paid_amount_without_gst);if(without===null)without=parseAmount(row.paid_amount_without_tax);if(without===null)without=parseAmount(row.amount_without_gst);let gst=parseAmount(row.gst_amount);if(gst===null)gst=parseAmount(row.tax_amount);if(without===null&&paid>0)without=paid/1.05;if(gst===null&&paid>0)gst=paid-Number(without||0);return{...row,posting_date:row.invoice_date||row.posting_date||'',referring_employee:String(row.referring_employee||row.custom_referring_name||row.referring_name||'').trim(),incentive_employee:String(row.incentive_employee||row.custom_incentive_employee_name||row.incentive_employee_name||'').trim(),paid_amount:round(paid),tax_amount:round(gst),paid_amount_without_tax:round(without)};}
function rowKey(row){if(row.invoice)return`invoice|${String(row.branch||'').trim()}|${String(row.invoice).trim()}`;return JSON.stringify([row.branch,row.posting_date,row.customer,row.booking_type,row.referring_employee,row.incentive_employee,row.mode_of_payment,row.paid_amount,row.tax_amount,row.paid_amount_without_tax,row.grand_total,row.outstanding_amount]);}
async function getBranches(){branchReady.value=false;branchError.value='';try{const response=await request('frappe.client.get_list',{args:{doctype:'Branch',fields:['name'],limit_page_length:200,order_by:'name asc'},csrfToken:session.csrf_token});const names=(response.message||[]).map(row=>String(row.name||'').trim()).filter(Boolean);permittedBranches.value=[...new Set(names)];allBranchAccess.value=canUseAll();branchRestricted.value=!allBranchAccess.value;if(!allBranchAccess.value&&!names.length)throw new Error('No permitted Branch was returned for this login.');if(!allBranchAccess.value&&names.length===1)branch.value=names[0];branchReady.value=true;}catch(e){branchError.value=e.message;branchReady.value=false;}}
async function runOneBranch(state,requestedBranch,signal){
  const filters={from_date:state.fromDate,to_date:state.toDate,branch:requestedBranch||''};const params=new URLSearchParams({report_name:reportName,filters:JSON.stringify(filters),ignore_prepared_report:'1',are_default_filters:'false'});
  let response;try{response=await fetch(apiUrl('/api/method/frappe.desk.query_report.run?'+params.toString()),{method:'GET',credentials:apiCredentials(),signal,headers:{Accept:'application/json'}});}catch(e){if(e.name==='AbortError')throw e;throw new Error('Could not reach the report server. Check your connection and retry.');}
  const body=await response.json().catch(()=>({}));if(!response.ok||body.exc_type){let message=body.message||body.exception||'Sales Master Data report failed.';try{const messages=JSON.parse(body._server_messages||'[]');if(messages[0])message=JSON.parse(messages[0]).message||message;}catch{}throw new Error(String(message).replace(/<[^>]*>/g,'').split('\n').pop());}
  const result=Array.isArray(body.message?.result)?body.message.result:[];return result.filter(row=>row&&typeof row==='object'&&!Array.isArray(row)&&!(row.is_total_row===true||row.is_total_row===1||row.invoice==='Total')).map((row,index)=>{const copy=normalizeRow(row),normalizedRequested=String(requestedBranch||'').trim();copy.__sourceIndex=index;copy.__requestedBranch=normalizedRequested;if(normalizedRequested&&String(copy.branch||'').trim()!==normalizedRequested)return null;return copy;}).filter(Boolean);
}
function validate(){if(!from.value||!to.value){error.value='Choose both report dates.';return false;}if(from.value>to.value){error.value='From Date cannot be after To Date.';return false;}const pFrom=parseAmount(paidFrom.value),pTo=parseAmount(paidTo.value),out=parseAmount(outstandingValue.value);if(paidFrom.value.trim()&&pFrom===null){error.value='Enter a valid Paid Amount From value.';return false;}if(paidTo.value.trim()&&pTo===null){error.value='Enter a valid Paid Amount To value.';return false;}if(pFrom!==null&&pTo!==null&&pFrom>pTo){error.value='Paid Amount From cannot exceed Paid Amount To.';return false;}if(outstandingOperator.value&&out===null){error.value='Enter a valid Outstanding Amount.';return false;}if(branchRestricted.value&&branch.value&&!permittedBranches.value.includes(branch.value)){error.value='You do not have access to the selected branch.';return false;}if(branchRestricted.value&&permittedBranches.value.length===1&&!branch.value)branch.value=permittedBranches.value[0];return true;}
function stateSnapshot(){return{fromDate:from.value,toDate:to.value,branch:branch.value,salesPerson:salesPerson.value,bookingType:bookingType.value,modeOfPayment:modeOfPayment.value,customer:customer.value.trim().toLowerCase(),paidFrom:parseAmount(paidFrom.value),paidTo:parseAmount(paidTo.value),outstandingOperator:outstandingOperator.value,outstandingValue:parseAmount(outstandingValue.value)};}
function applyLocalFilters(source,state){return source.filter(row=>{
  if(branchRestricted.value&&permittedBranches.value.length&&!permittedBranches.value.includes(String(row.branch||'')))return false;
  if(state.branch&&row.branch!==state.branch)return false;
  if(state.salesPerson&&![row.referring_employee,row.incentive_employee].some(name=>String(name||'').trim().toLowerCase()===state.salesPerson.toLowerCase()))return false;
  if(state.bookingType&&row.booking_type!==state.bookingType)return false;
  if(state.modeOfPayment&&!String(row.mode_of_payment||'').includes(state.modeOfPayment))return false;
  if(state.customer&&![row.customer,row.invoice,row.mobile_no,row.customer_id,row.patient,row.patient_name,row.client_name].some(value=>String(value||'').toLowerCase().includes(state.customer)))return false;
  const paid=parseAmount(row.paid_amount)||0;if(state.paidFrom!==null&&paid<state.paidFrom)return false;if(state.paidTo!==null&&paid>state.paidTo)return false;
  const outstanding=parseAmount(row.outstanding_amount)||0;if(state.outstandingOperator==='>'&&!(outstanding>state.outstandingValue))return false;if(state.outstandingOperator==='>='&&!(outstanding>=state.outstandingValue))return false;if(state.outstandingOperator==='<'&&!(outstanding<state.outstandingValue))return false;if(state.outstandingOperator==='<='&&!(outstanding<=state.outstandingValue))return false;return true;
});}
function updateEmployees(){const names=new Set();for(const row of rows.value){if(row.referring_employee)names.add(row.referring_employee);if(row.incentive_employee)names.add(row.incentive_employee);}if(salesPerson.value&&!names.has(salesPerson.value))names.add(salesPerson.value);employees.value=[...names].sort((a,b)=>a.localeCompare(b,undefined,{sensitivity:'base'}));}
async function applyFilters(){if(loading.value||!branchReady.value||!validate())return;controller?.abort();const ctrl=new AbortController();controller=ctrl;loading.value=true;error.value='';notice.value='';filteredRows.value=[];page.value=1;const state=stateSnapshot();
  try{let branchesToLoad;if(branchRestricted.value&&!state.branch&&permittedBranches.value.length>1)branchesToLoad=permittedBranches.value.slice();else branchesToLoad=[state.branch||''];const groups=await Promise.all(branchesToLoad.map(name=>runOneBranch(state,name,ctrl.signal)));if(!alive||controller!==ctrl)return;const seen=new Set();rows.value=[];for(const group of groups)for(const row of group){const key=rowKey(row);if(!seen.has(key)){seen.add(key);rows.value.push(row);}}updateEmployees();filteredRows.value=applyLocalFilters(rows.value,state);reportLoaded.value=true;notice.value=`Loaded ${filteredRows.value.length.toLocaleString('en-IN')} matching records.`;}
  catch(e){if(alive&&controller===ctrl&&e.name!=='AbortError'){error.value=e.message;rows.value=[];filteredRows.value=[];employees.value=[];reportLoaded.value=false;}}
  finally{if(alive&&controller===ctrl)loading.value=false;}
}
function setPreset(key){quick.value=key;const range=dateRange(key);from.value=range.from;to.value=range.to;notice.value='Date range changed. Click Apply Filters.';}
function formatDate(value){if(!value)return'';const parts=String(value).slice(0,10).split('-');return parts.length===3?`${parts[2]}-${parts[1]}-${parts[0]}`:String(value);}
function salesPeople(row){const ref=String(row.referring_employee||'').trim(),inc=String(row.incentive_employee||'').trim();return ref&&inc?`${ref} / ${inc}`:ref||inc;}
function rowValue(row,key){if(key==='sales_people')return salesPeople(row);if(key==='posting_date')return formatDate(row.posting_date);if(['paid_amount','tax_amount','paid_amount_without_tax','grand_total','outstanding_amount'].includes(key))return money(row[key]);return row[key]||'';}
const totals=computed(()=>Object.fromEntries(['paid_amount','tax_amount','paid_amount_without_tax','grand_total','outstanding_amount'].map(key=>[key,filteredRows.value.reduce((sum,row)=>sum+(parseAmount(row[key])||0),0)])));
function csvCell(value){const text=String(value??'');return /[",\r\n]/.test(text)?`"${text.replace(/"/g,'""')}"`:text;}
function xmlCell(value){return String(value??'').replace(/[<>&'\"]/g,c=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','\"':'&quot;'}[c]));}
function exportRows(){if(!reportLoaded.value||!filteredRows.value.length){error.value='There are no filtered rows to download.';return;}const header=cols.map(([,label])=>label),numericKeys=new Set(['paid_amount','tax_amount','paid_amount_without_tax','grand_total','outstanding_amount']),values=filteredRows.value.map(row=>cols.map(([key])=>key==='posting_date'?formatDate(row.posting_date):key==='sales_people'?salesPeople(row):numericKeys.has(key)?parseAmount(row[key])??0:row[key]??''));const base=`Life_Sales_Master_${from.value}_to_${to.value}`;if(format.value==='csv'){const lines=[header,...values].map(row=>row.map(csvCell).join(',')).join('\r\n');downloadBlob(base+'.csv',new Blob(['\ufeff'+lines],{type:'text/csv;charset=utf-8'}));}else{const numeric=new Set(['Paid w/ GST','GST Amt','Paid w/o GST','Grand Total','Outstanding']);const all=[header,...values];const rowsXml=all.map((row,i)=>`<Row>${row.map((v,j)=>`<Cell><Data ss:Type="${i&&numeric.has(header[j])?'Number':'String'}">${xmlCell(v)}</Data></Cell>`).join('')}</Row>`).join('');const content=`<?xml version="1.0"?><Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"><Worksheet ss:Name="Sales Master"><Table>${rowsXml}</Table></Worksheet></Workbook>`;downloadBlob(base+'.xls',new Blob([content],{type:'application/vnd.ms-excel;charset=utf-8'}));}notice.value=`${format.value==='csv'?'CSV':'Excel'} download started for ${filteredRows.value.length.toLocaleString('en-IN')} filtered records.`;}
function downloadBlob(filename,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function resetFilters(){const range=dateRange('thismonth');from.value=range.from;to.value=range.to;quick.value='thismonth';branch.value=branchRestricted.value&&permittedBranches.value.length===1?permittedBranches.value[0]:'';salesPerson.value='';bookingType.value='';modeOfPayment.value='';customer.value='';paidFrom.value='';paidTo.value='';outstandingOperator.value='';outstandingValue.value='';applyFilters();}
onMounted(()=>{const range=dateRange('thismonth');from.value=range.from;to.value=range.to;getBranches().then(()=>{if(alive&&branchReady.value)applyFilters();});});
onBeforeUnmount(()=>{alive=false;controller?.abort();});
</script>

<template>
  <section class="sales-master">
    <header class="sm-header"><h1>Life Sales Master Data</h1><p>Referral report · paid and outstanding invoice details</p></header>
    <section class="sm-filters">
      <div class="sm-date-grid"><label>From Date<input v-model="from" type="date" @change="quick=''" /></label><label>To Date<input v-model="to" type="date" @change="quick=''" /></label></div>
      <div class="sm-quick"><button v-for="[key,label] in presets" :key="key" :class="{active:quick===key}" @click="setPreset(key)">{{ label }}</button></div>
      <div class="sm-grid3"><label>Branch<select v-model="branch" :disabled="!branchReady||branchRestricted&&permittedBranches.length===1"><option value="">{{ branchRestricted?'All Permitted Branches':'All Branches' }}</option><option v-for="name in permittedBranches" :key="name">{{ name }}</option></select></label><label>Sales Person / Employee<select v-model="salesPerson"><option value="">All Employees</option><option v-for="name in employees" :key="name">{{ name }}</option></select></label><label>Booking Type<select v-model="bookingType"><option value="">All Booking Types</option><option>Call Center</option><option>DIRECT WALKIN</option><option>Existing Customer</option><option>InHouse</option><option>Reference</option><option>Unjoined</option><option>Walk In</option></select></label></div>
      <div class="sm-grid4"><label>Mode of Payment<select v-model="modeOfPayment"><option value="">All Modes</option><option>Bajaj Card Charges</option><option>Carepay</option><option>Cash</option><option>Credit Card</option><option>Debit Card</option><option>Fibe Finance</option><option>Online Transfer(Bank)</option><option>Razorpay Software Pvt Ltd -Link</option><option>Sai Roshini Card Charges</option><option>Savein Fintech Card Charges</option><option>ShopSE</option><option>mobile payments</option></select></label><label>Customer Name / Mobile / ID<input v-model="customer" placeholder="Search…" /></label><label>Paid Amount From (₹)<input v-model="paidFrom" inputmode="decimal" placeholder="Min" /></label><label>Paid Amount To (₹)<input v-model="paidTo" inputmode="decimal" placeholder="Max" /></label></div>
      <div class="sm-outstanding"><div><strong>Outstanding Amount Filter</strong><p>Filters the Outstanding column only. It is independent of Paid Amount.</p></div><label>Condition<select v-model="outstandingOperator"><option value="">No condition</option><option value=">">Greater than (&gt;)</option><option value=">=">Greater than or equal (&gt;=)</option><option value="<">Less than (&lt;)</option><option value="<=">Less than or equal (&lt;=)</option></select></label><label>Outstanding Amount (₹)<input v-model="outstandingValue" inputmode="decimal" placeholder="Enter amount" :disabled="!outstandingOperator" /></label></div>
      <div class="sm-apply"><p>Change filters, then apply to refresh the report.</p><div><button :disabled="loading||!branchReady" @click="resetFilters">Reset</button><button class="sm-primary" :disabled="loading||!branchReady" @click="applyFilters">{{ loading?'Loading…':'Apply Filters' }}</button></div></div>
    </section>
    <section class="sm-footer"><p>Preview includes 12 visible columns — Invoice, Posting Date, Branch, Customer, Booking Type, Sales Person, Mode of Payment, Paid with GST, GST Amount, Paid without GST, Grand Total and Outstanding.</p><div><span>Download Format</span><button :class="{active:format==='xlsx'}" @click="format='xlsx'">Excel</button><button :class="{active:format==='csv'}" @click="format='csv'">CSV</button><button class="sm-gold" :disabled="loading||!reportLoaded" @click="exportRows">Generate &amp; Download</button></div></section>
    <p v-if="branchError" class="sm-error" role="alert">{{ branchError }}. Report loading has been blocked because branch access could not be verified.</p><p v-else-if="error" class="sm-error" role="alert">{{ error }}</p><p v-else-if="notice" class="sm-notice" role="status">{{ notice }}</p><p v-else-if="loading" class="sm-notice" role="status">Loading report…</p>
    <section v-if="reportLoaded" class="sm-table-wrap" tabindex="0" role="region" aria-label="Sales master report"><table><thead><tr><th v-for="[,label] in cols" :key="label">{{ label }}</th></tr></thead><tbody><tr v-for="(row,index) in visibleRows" :key="row.invoice+'-'+row.branch+'-'+index"><td v-for="[key] in cols" :key="key" :class="{'sm-number':['paid_amount','tax_amount','paid_amount_without_tax','grand_total','outstanding_amount'].includes(key)}"><template v-if="key==='sales_people'"><span v-if="row.referring_employee">{{ row.referring_employee }}<template v-if="row.incentive_employee"> /</template></span><span v-if="row.incentive_employee">{{ row.incentive_employee }}</span></template><template v-else>{{ rowValue(row,key) }}</template></td></tr><tr v-if="!visibleRows.length"><td colspan="12" class="sm-empty">No records match the selected filters.</td></tr></tbody><tfoot><tr><td>TOTAL ({{ filteredRows.length }} rows)</td><td></td><td></td><td></td><td></td><td></td><td></td><td>{{ money(totals.paid_amount) }}</td><td>{{ money(totals.tax_amount) }}</td><td>{{ money(totals.paid_amount_without_tax) }}</td><td>{{ money(totals.grand_total) }}</td><td>{{ money(totals.outstanding_amount) }}</td></tr></tfoot></table><footer class="sm-pagination"><button :disabled="page<=1" @click="page=1">« First</button><button :disabled="page<=1" @click="page--">‹ Prev</button><button v-for="p in Array.from({length:Math.min(5,pageCount)},(_,i)=>Math.max(1,Math.min(pageCount-4,page-2))+i).filter((n,i,a)=>n<=pageCount&&a.indexOf(n)===i)" :key="p" :class="{active:page===p}" @click="page=p">{{ p }}</button><button :disabled="page>=pageCount" @click="page++">Next ›</button><button :disabled="page>=pageCount" @click="page=pageCount">Last »</button><span>Page {{ page }} of {{ pageCount }} · {{ recordCount }}<template v-if="branch"> · Branch: {{ branch }}</template></span></footer></section>
  </section>
</template>
