<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { request } from '../api/http';
import { session } from '../lib/session';
import '../styles/vendors.css';

const pageSize=40;
const query=ref(''),group=ref(''),country=ref(''),status=ref('active'),groups=ref([]),countries=ref([]),rows=ref([]),total=ref(0),page=ref(1),loading=ref(false),error=ref(''),selected=ref(null);
let controller,groupController,alive=true,searchTimer;
const pages=computed(()=>Math.max(1,Math.ceil(total.value/pageSize)));
const from=computed(()=>total.value?((page.value-1)*pageSize+1):0),to=computed(()=>Math.min(page.value*pageSize,total.value));
const pageRows=computed(()=>query.value.trim()?rows.value.slice((page.value-1)*pageSize,page.value*pageSize):rows.value);
const enabledCount=computed(()=>pageRows.value.filter(r=>!Number(r.disabled)).length);
const headers={'Content-Type':'application/json','X-Frappe-CSRF-Token':session.csrf_token||''};
function filters(){const f=[];if(group.value)f.push(['Supplier','supplier_group','=',group.value]);if(country.value)f.push(['Supplier','country','=',country.value]);if(status.value==='active')f.push(['Supplier','disabled','=',0]);if(status.value==='disabled')f.push(['Supplier','disabled','=',1]);return f;}
async function load(target=1){page.value=target;controller?.abort();const current=new AbortController();controller=current;loading.value=true;error.value='';try{const text=query.value.trim(),args={doctype:'Supplier',fields:['name','supplier_name','supplier_group','supplier_type','country','disabled','creation'],filters:filters(),limit_start:text?0:(target-1)*pageSize,limit_page_length:text?5000:pageSize,order_by:'supplier_name asc, name asc'};if(text)args.or_filters=[['Supplier','supplier_name','like',`%${text}%`],['Supplier','name','like',`%${text}%`]];const list=await request('frappe.client.get_list',{args,signal:current.signal,csrfToken:session.csrf_token});let count;if(text)count={message:(list.message||[]).length};else count=await request('frappe.client.get_count',{args:{doctype:'Supplier',filters:filters()},signal:current.signal,csrfToken:session.csrf_token});if(!alive||controller!==current)return;rows.value=list.message||[];total.value=Number(count.message||0);if(target>pages.value&&target>1)load(pages.value);}catch(e){if(alive&&controller===current&&e.name!=='AbortError'){error.value=e.message;rows.value=[];total.value=0;}}finally{if(alive&&controller===current)loading.value=false;}}
async function loadGroups(){groupController?.abort();const c=new AbortController();groupController=c;try{const [g,co]=await Promise.all([request('frappe.client.get_list',{args:{doctype:'Supplier Group',fields:['name'],limit_page_length:500,order_by:'name asc'},signal:c.signal,csrfToken:session.csrf_token}),request('frappe.client.get_list',{args:{doctype:'Supplier',fields:['country'],filters:[['Supplier','country','!=','']],limit_page_length:5000,order_by:'country asc'},signal:c.signal,csrfToken:session.csrf_token})]);if(!alive||groupController!==c)return;groups.value=(g.message||[]).map(x=>x.name).filter(Boolean);countries.value=[...new Set((co.message||[]).map(x=>x.country).filter(Boolean))].sort((a,b)=>a.localeCompare(b));}catch(e){if(e.name!=='AbortError'&&alive)error.value=e.message;}}
function scheduleSearch(){clearTimeout(searchTimer);searchTimer=setTimeout(()=>load(1),280);}
function open(row){selected.value={...row,loading:true,error:''};request('frappe.client.get',{args:{doctype:'Supplier',name:row.name},csrfToken:session.csrf_token}).then(result=>{if(selected.value?.name===row.name)selected.value={...result.message,loading:false,error:''};}).catch(e=>{if(selected.value?.name===row.name)selected.value={...row,loading:false,error:e.message};});}
function dateText(value){return value?new Date(`${String(value).slice(0,10)}T00:00:00`).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';}
watch([group,country,status],()=>load(1));
onMounted(()=>{loadGroups();load(1);});
onBeforeUnmount(()=>{alive=false;controller?.abort();groupController?.abort();clearTimeout(searchTimer);});
</script>

<template>
  <main class="vendors-page"><header class="vp-header"><div><span class="vp-eyebrow">STOCK &amp; PURCHASE</span><h1>Vendors</h1><p>Supplier directory</p></div><button class="vp-refresh" :disabled="loading" @click="load(page)">{{ loading?'Loading…':'↻ Refresh' }}</button></header>
    <section class="vp-filters"><label class="vp-search">Search supplier<input v-model="query" type="search" placeholder="Supplier name or ID" @input="scheduleSearch"></label><label>Supplier Group<select v-model="group"><option value="">All Groups</option><option v-for="name in groups" :key="name">{{ name }}</option></select></label><label>Country<select v-model="country"><option value="">All Countries</option><option v-for="name in countries" :key="name">{{ name }}</option></select></label><label>Status<select v-model="status"><option value="active">Active suppliers</option><option value="disabled">Disabled suppliers</option><option value="all">All suppliers</option></select></label></section>
    <p v-if="error" class="vp-error" role="alert">{{ error }}</p><p v-else-if="loading" class="vp-status" role="status">Loading suppliers…</p>
    <section class="vp-summary"><div><span>Matching Suppliers</span><strong>{{ total.toLocaleString('en-IN') }}</strong></div><div><span>Active on this page</span><strong>{{ enabledCount.toLocaleString('en-IN') }}</strong></div><div><span>Page</span><strong>{{ page }} / {{ pages }}</strong></div></section>
    <section class="vp-table-wrap" aria-label="Supplier list"><table><thead><tr><th>Supplier</th><th>Supplier ID</th><th>Group</th><th>Type</th><th>Country</th><th>Status</th><th>Created</th><th></th></tr></thead><tbody><tr v-for="row in pageRows" :key="row.name"><td><strong>{{ row.supplier_name||row.name }}</strong></td><td>{{ row.name }}</td><td>{{ row.supplier_group||'—' }}</td><td>{{ row.supplier_type||'—' }}</td><td>{{ row.country||'—' }}</td><td><span class="vp-badge" :class="Number(row.disabled)?'disabled':'active'">{{ Number(row.disabled)?'Disabled':'Active' }}</span></td><td>{{ dateText(row.creation) }}</td><td><button class="vp-view" @click="open(row)">View</button></td></tr><tr v-if="!loading&&!rows.length"><td colspan="8" class="vp-empty">No suppliers match these filters.</td></tr></tbody></table><footer class="vp-pager"><span>{{ from }}–{{ to }} of {{ total.toLocaleString('en-IN') }}<template v-if="query.trim()&&total>=5000"> (first 5,000 matching)</template></span><div><button :disabled="page<=1||loading" @click="load(1)">First</button><button :disabled="page<=1||loading" @click="load(page-1)">Previous</button><button :disabled="page>=pages||loading" @click="load(page+1)">Next</button><button :disabled="page>=pages||loading" @click="load(pages)">Last</button></div></footer></section>
    <div v-if="selected" class="vp-overlay" @click.self="selected=null"><section class="vp-dialog" role="dialog" aria-modal="true" aria-labelledby="vp-detail-title"><header><div><h2 id="vp-detail-title">{{ selected.supplier_name||selected.name }}</h2><p>{{ selected.name }}</p></div><button aria-label="Close" @click="selected=null">×</button></header><p v-if="selected.loading" class="vp-status">Loading supplier details…</p><p v-else-if="selected.error" class="vp-error">{{ selected.error }}</p><dl v-else class="vp-detail-grid"><div><dt>Supplier Group</dt><dd>{{ selected.supplier_group||'—' }}</dd></div><div><dt>Supplier Type</dt><dd>{{ selected.supplier_type||'—' }}</dd></div><div><dt>Country</dt><dd>{{ selected.country||'—' }}</dd></div><div><dt>Tax ID</dt><dd>{{ selected.tax_id||selected.gstin||'—' }}</dd></div><div><dt>Email</dt><dd>{{ selected.email_id||'—' }}</dd></div><div><dt>Phone</dt><dd>{{ selected.mobile_no||selected.phone||'—' }}</dd></div><div><dt>Website</dt><dd>{{ selected.website||'—' }}</dd></div><div><dt>Status</dt><dd>{{ Number(selected.disabled)?'Disabled':'Active' }}</dd></div><div class="vp-address"><dt>Primary Address</dt><dd>{{ selected.primary_address||'—' }}</dd></div></dl><footer><button @click="selected=null">Close</button></footer></section></div>
  </main>
</template>
